name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USER }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "./"
        target: "/tmp/api.ozeliurs.com"

    - name: Delete contents of server folder and copy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USER }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: sudo touch /var/www/api/tmp && \
        sudo rm -r /var/www/api/* && \
        sudo cp /tmp/api.ozeliurs.com/www/* /var/www/api/ && \
        sudo pip install -r /var/www/api/requirements.txt && \
        sudo rm /etc/systemd/system/api.ozeliurs.com.service && \
        sudo cp /tmp/api.ozeliurs.com/api.ozeliurs.com.service /etc/systemd/system/ && \
        sudo rm -r /tmp/api.ozeliurs.com && \
        sudo chown -R www-data /var/www/api/ && \
        sudo systemctl daemon-reload && \
        sudo systemctl restart api.ozeliurs.com.service
